# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b47550abd341aa7b9f91c2805daf453f390509a258c423b0dd2f012c084596fba9fbab648b5a48c00780e0cf1afbf472c5cd4fe09a0824cdb8377ee0f7cfa043

test:
  secret_key_base: b4d1051e774f333dc5025ff53268d3b9e68ff0c7d1db7c61ee00901b524f6a938716142b36f401e38acba5dbd2c1606ffff2f4eea1f0a5d86bee599159fdc3e0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
